### ISSUE TITLE
contract  max code size exceeded

### ISSUE THREAD

**Issue by int19890411** [immutable/contracts#169]
### You example not working

**When compile** :
npx hardhat compile
Warning: Contract code size is 38326 bytes and exceeds 24576 bytes (a limit introduced in Spurious Dragon). This contract may not be deployable on Mainnet. Consider enabling the optimizer (with a low "runs" value!), turning off revert
strings, or using libraries.
 --> contracts/Test.sol:4:1:
 
 **When deploy to https://rpc.testnet.immutable.com/** 
 npx hardhat run scripts/deployImmutable.js --network immutableTestnet
Deploy contracts:

C:\Users\pc\wkspace\immutablecontracts\node_modules\hardhat\src\internal\core\providers\http.ts:88
      const error = new ProviderError(
                    ^
ProviderError: max code size exceeded
    at HttpProvider.request (C:\Users\pc\wkspace\immutablecontracts\node_modules\hardhat\src\internal\core\providers\http.ts:88:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HardhatEthersProvider.estimateGas (C:\Users\pc\wkspace\immutablecontracts\node_modules\@nomicfoundation\hardhat-ethers\src\internal\hardhat-ethers-provider.ts:237:27)
    at C:\Users\pc\wkspace\immutablecontracts\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:235:35
    at async Promise.all (index 0)
    at HardhatEthersSigner._sendUncheckedTransaction (C:\Users\pc\wkspace\immutablecontracts\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:256:7)
    at HardhatEthersSigner.sendTransaction (C:\Users\pc\wkspace\immutablecontracts\node_modules\@nomicfoundation\hardhat-ethers\src\signers.ts:125:18)
    at ContractFactory.deploy (C:\Users\pc\wkspace\immutablecontracts\node_modules\ethers\src.ts\contract\factory.ts:111:24)
    at main (C:\Users\pc\wkspace\immutablecontracts\scripts\deployImmutable.js:29:20)

 
module.exports = {
  solidity: "0.8.19",
  settings: {
    optimizer: {
      enabled: true,
      runs: 200
    }
  },

**Comment by int19890411** [comment]
![image](https://github.com/immutable/contracts/assets/11244718/88948cd0-d176-4fd4-b1ae-2685170a19ce)

**Comment by drinkcoffee** [comment]
@int19890411  we are investigating this issue and will get back to you shortly.

**Comment by jasonzwli** [comment]
@int19890411 can you follow the steps here https://docs.immutable.com/docs/zkEVM/deploy-contracts/deploy and report back if you still have a problem? Your error suggests you to add extra config options to your hardhat config.

**Comment by drinkcoffee** [comment]
@int19890411  did you have a chance to check this, based on @jasonzwli 's message?

**Comment by int19890411** [comment]
I found the problem.
The optimizer was specified incorrectly.
Used settings from the previous version of Hardhat

**Comment by drinkcoffee** [comment]
Good that you solved the problem. Thank you for closing the issue.
